package bp

import (
	"text/template"
)

var endpointTemplate = `// AUTOGENERATED CODE.
// !!  DO NOT EDIT  !!

package {{ .Pkg }}http

import (
	"context"
	"fmt"
	"{{ .PkgPath }}"
	"github.com/go-kit/kit/endpoint"
)

{{ range $func := .Funcs }}
func make{{ .Name }}Endpoint(s {{ $.Pkg }}.{{ $.ServiceName }}) endpoint.Endpoint {
	return func(ctx context.Context, rawReq any) (res any, err error) {
		{{ range $args := .Arguments }}
		var {{ .Name }} {{ .Type.Type "DynamicField" }}
		var {{ .Name }}ok bool
		if {{ .Name }}, {{ .Name }}ok = rawReq.({{ .Type.Type "DynamicField" }}); !{{ .Name }}ok {
			return nil, fmt.Errorf("bad request")
		}
		{{ end }}
		res, err = s.{{ .Name }}(ctx, req)

		return
	}
}
{{ end }}
`

func NewEndpointTemplate(serviceName string) *template.Template {
	t := template.New(serviceName)
	t.Funcs(map[string]any{})
	return template.Must(t.Parse(endpointTemplate))
}
